#!/usr/bin/env bash
# this script transfers a file from our localhost to our server
# we check if the arguments are equal to 4 or less than
# we set the strcthostkeychecking to no
# first_arg is file to be transfered, second_arg path
# thrid_arg is the ip address together with its username
# fourth_arg is the path to the ssh key
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
