#!/usr/bin/env bash
#Ping uses ICMP to ensure that the Network device remain online and troubleshoots
#while the -c allows for ping to count the number of times the packets are returned
#it then terminates the process after the specified time expires in this 5

if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 $1
fi
