#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely with
#adding a sleep 2 in between each iteration.
#Displays I am invincible!!! in between each iteration.
#we can use ctrl+c to stop or use the previous file 6

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
