#!/usr/bin/env bash
# echoes Best School 10 times using while until 9 where it prints Hi

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
