#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and displays the following;
#echoes bad luck for the 4th iteration
#echoes good luck for the 8th iteration
#echoes Best School for all other iterations

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
