#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#it should only displays the part of the name after the first dash we use cut
#for directory we use -d

list=$(ls)
for i in $list;
do
  echo "$i" | cut -d '-' -f2
done
