#!/usr/bin/env bash
#a Bash script that displays all active IPv4 IPs on machines its executed on
#Note that we can see our localhost IP :)

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
